### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Thebigbignooby** [static-dev/spike#47]
I just followed the tutorial, and this is what I get
```
λ spike watch
Unhandled rejection TypeError: Cannot read property 'error' of undefined
    at processedFiles.forEach (C:\nvm\v6.9.2\node_modules\spike\node_modules\spike-core\lib\plugin.js:59:16)
    at Array.forEach (native)
    at Compiler.compiler.plugin (C:\nvm\v6.9.2\node_modules\spike\node_modules\spike-core\lib\plugin.js:52:22)
    at Compiler.applyPluginsAsync (C:\nvm\v6.9.2\node_modules\spike\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.emitAssets (C:\nvm\v6.9.2\node_modules\spike\node_modules\webpack\lib\Compiler.js:226:7)
    at Watching.<anonymous> (C:\nvm\v6.9.2\node_modules\spike\node_modules\webpack\lib\Compiler.js:54:18)
    at C:\nvm\v6.9.2\node_modules\spike\node_modules\webpack\lib\Compiler.js:403:12
    at Compiler.next (C:\nvm\v6.9.2\node_modules\spike\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> (C:\nvm\v6.9.2\node_modules\spike\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.next (C:\nvm\v6.9.2\node_modules\spike\node_modules\tapable\lib\Tapable.js:69:14)
    at C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\hard-source-webpack-plugin\index.js:1469:7
    at tryCatcher (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\rory\dev\CLIENTS\mathonnet\v1\node_modules\bluebird\js\release\promise_array.js:143:14)
```
:'(

**Comment by Thebigbignooby** [comment]
Samething for `spike compile`

**Comment by jescalan** [comment]
I'm sorry, spike doesn't currently support windows. We are happy to accept PRs to help with the support though!

**Comment by Thebigbignooby** [comment]
well this is disappointing :-1: :(  :'( Do you know what the problem is ? 
would love to contribute but I don't have the time

**Comment by jescalan** [comment]
I'm sorry! I just don't have a windows machine to test on. Also, I have no motivation to burn the hours it would take, to be honest. I'm sponsored by my company to work on this software, and nobody at my company uses windows. I also don't personally use windows, nor do I know any software developers who do, so it would just be working for free for no tangible benefit to myself or the project's sponsors, and I have a lot of other projects that are a higher priority at the current moment.

That being said, I am not opposed to having windows support, in fact I would love for it to happen. This is why I mentioned to accepting PRs in the last comment! If there are windows users interested in spike, we should make it happen. I just don't have the time, motivation, or equipment to do 100% of it myself. I am more than happy to help out and support as much as I can if someone else is willing to lead the effort. This is open source, let's work together to make great software 😁

**Comment by jescalan** [comment]
I'd also like to just add this piece here as food for thought:

https://medium.com/static-dev/willingness-to-contribute-required-709bc1a09eaf

I get a lot of people asking for features or faster bugfixes but saying they don't have the time or experience to contribute themselves. If you don't have the time or experience to contribute, I would be careful using OSS at all, to be honest. What if you use someone's project and find a bug that needs to be fixed or your app goes down? You are not paying for priority support on any OSS project you use, presumably, so it's your responsibility to fix it. If you don't have the time or experience to do so, you have put yourself into a very unfortunate situation that could easily lead to losing money and/or your job.

Also, contributing to open source projects is an incredibly important part of the community, and is a great opportunity to learn. I go out of my way to be particularly responsive and supportive to anyone that will take the time to try to contribute, you can verify this with [our community](https://gitter.im/static-dev/spike) if you'd like. This makes it a great place to start getting involved if/when you find a bit of free time. Plus, when we start actually marketing this project and it goes to 1 million stars, you'll be famous for being on the contributors list 😉
