### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by janwirth** [static-dev/spike#48]
First off - thank you for this awesome tool. Love it as much as I roots.
I discovered a few problems I want to share with you.
Those problems are combined in this issue in case I am using things completely wrong / unicorn bug.
However, those problems occur for me on both node 6 / 7 on Ubuntu 16.04 and macOS 10.12.2 (16C67)

I hope you can help me with this :)

**Creating a new project throws deprecation warning**
```
[~] spike new myproject                                                                                           
▸ initializing template
? What is the name of your project? (node:3676) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**No hot code pushes**
Every change to my files will reload the entire page and clear the state.
The webpack setup created by vue-cli has all the bells and whistles you can dream of. If I recall correctly, roots would also update CSS without reload.

**Build errors throw a stack that is of little use locating the error (JS, HTML, CSS ...):**
```
✗ ERROR
Error
    at NormalModule.onModuleBuildFailed (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/postcss-loader/index.js:139:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
⚠ WARNING
Error
    at NormalModule.onModuleBuildFailed (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /Users/janwirth/.nvm/versions/node/v7.4.0/lib/node_modules/spike/node_modules/postcss-loader/index.js:139:13
    at process._tickCallback (internal/process/next_tick.js:103:7)```

**Comment by jescalan** [comment]
Hi there! Thanks for bringing these up.

The first issue is with sprout, and only happens on node 7. Could you file it as an issue in the [sprout repo](https://github.com/carrot/sprout) by any chance?

For the second, roots did a full page reload, and you can only do hot code pushes if you are using a front-end framework that supports this. Spike is intended for use with all sorts of different types of sites or frameworks though, so I don't want to commit to this. There are other projects that are built specifically on top of react that offer this functionality, but it ties your site structure to react. In the future I'd love to add the ability to link up hot reloads if you are using a supported front-end framework, however at the moment I have a lot of other things on my list that come before it.

For the error thing, thank you for the heads up. This is partially webpack and partially spike's error handling. Any use-case that will effectively replicate bad stack traces like this would be helpful in debugging.

In general, it's most helpful to get one issue per issue as well. This is totally fine, just for the future!

**Comment by janwirth** [comment]
Thank you for that quick response.

You can reproduce the error using https://github.com/FranzSkuffka/spike-error

JS hot reload being a framework thing and hard to optimize for makes sense. ROI just is not there.
What about CS?

**Comment by jescalan** [comment]
What do you mean by CS?

**Comment by janwirth** [comment]
CSS, sorry. Typo.
Is that also framework-specific?

I have zero experience with hot-module replacement on webpack. But it seems to me https://github.com/webpack-contrib/extract-text-webpack-plugin is the way to go.

**Comment by jescalan** [comment]
css hot reload is supposedly handled through browsersync, which we use. I don't have the time nor motivation to look into this right now, but you are welcome to if you'd like!

The extract text plugin doesn't really have anything to do with hot reloads, but is a cool plugin!

**Comment by janwirth** [comment]
Sure, as always, thanks for the support. I have my own share of maintaining to do then I will take a look :) Do you mean it should be live reloading already or can I contribute the implementation?

**Comment by jescalan** [comment]
I feel like it should be injecting the css already, maybe there's an option to be flipped on, maybe it's not working... not entirely sure right now! Poke around and see : )

Spike is much smaller and simpler of a core than roots, so it should be less intimidating.

**Comment by janwirth** [comment]
I renamed this to Error reporting so that we have a cleanly-focused issue.

Any progress?

**Comment by crivera** [comment]
i have the same issue.

i changed a few files and now after compilation i always get:

`spike watch
✗ ERROR
Error
    at NormalModule.onModuleBuildFailed (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at tryCatchReject (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/spike/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/spike/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
⚠ WARNING
Error
    at NormalModule.onModuleBuildFailed (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/usr/local/lib/node_modules/spike/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at tryCatchReject (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/spike/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/spike/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

unfortunately this does not tell me anything

**Comment by janwirth** [comment]
@crivera if you're wondering about updates, I was just taking a look and saw that @jescalan solved this already. :) Thanks!

You can install it like this: `npm i https://github.com/static-dev/spike.git\#e2524962fca9d947ce538747cd5bc712a4dae696 -g`

**Comment by crivera** [comment]
cool thanks ill give it a shot

**Comment by janwirth** [comment]
Bump @jescalan for a new release :)

**Comment by jescalan** [comment]
So right now I'm working on the next version of spike which is based on webpack2, trying to get that out. The patch was accepted to webpack2, but has not yet been released.

The issue with back patching this is that not all errors will render correctly when using `toString`, if im not mistaken, so I don't want to push this to solve this use case and break another...

**Comment by janwirth** [comment]
How does spike compare to https://github.com/vuejs-templates/webpack? I kind of like this tool for scaffolding as well. Maybe spike can profit from .some of the solutions there.

**Comment by jescalan** [comment]
Very off-topic, but what you have linked there is a template for a single page app vue project. Spike is a full static site generator that can be used with any client-side framework and can generate static views.

An explicit goal of spike is not to tie to to a specific client-side framework, because as we all know, client-side frameworks come and go, and additionally there isn't a single one that is appropriate to be used for every project. I would be interested to hear which of the solutions you like. Perhaps they could be built into a vue-specific template that could be used with spike (along the same lines as the default template or the sugarfree one).
