### ISSUE TITLE
Fresh install: receiving TypeError

### ISSUE THREAD

**Issue by kildareflare** [static-dev/spike#78]
Hi, keen to check this generator out, but running into problems on a fresh install.

Windows 10
npm 5.4.2
node 6.11.3

`npm install -g spike`
`spike new test-project`
`spike watch`

I get the following warning 
`[BABEL] Note: The code generator has deoptimised the styling of "C:/Code/Projects/test/node_modules/browser-sync-ui                                                       /public/js/app.js.map" as it exceeds the max of "500KB".
`

And then a whole bunch of errors, starting with:
`✗ ERROR
{ ModuleBuildError: Module build failed: TypeError: Cannot read property 'type' of undefined
    at tree.reduce (C:\Users\rich\AppData\Roaming\npm\node_modules\spike\node_modules\reshape-code-gen\lib\index.js:37:1                                                       3)
at Array.reduce (native)
    at walk (C:\Users\rich\AppData\Roaming\npm\node_modules\spike\node_modules\reshape-code-gen\lib\index.js:35:15)
`
ending with:
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at writeOut (C:\Users\rich\AppData\Roaming\npm\node_modules\spike\node_modules\webpack\lib\Compiler.js:338:17)
    at C:\Users\rich\AppData\Roaming\npm\node_modules\spike\node_modules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)
`

**Comment by jescalan** [comment]
Hey there @kildareflare! Thanks for reporting this, and I'm so sorry you ran into this issue. To be honest, we have very few windows users, and I do not explicitly test windows every release. However, we do have a pretty extensive test suite which is passing on windows.

I will see if I can reproduce this later today. In the meantime, I might try upgrading your node version to the latest!

**Comment by kildareflare** [comment]
Hey, no worries- I realise that as a front end dev who uses windows I'm in the minority. ;0)
No rush as I've since moved onto a different generator.
